/*
 * this file is generated by yaGen (http://www.github.com/gekoh/yaGen)
 * please do not edit
 */
package com.github.gekoh.yagen.hst;

/**
 * @author Georg Kohlweiss
 */
public enum Operation {
    /**
     * insert
     */
    I,

    /**
     * update
     */
    U,

    /**
     * delete
     */
    D
}
